## Bem vindo 

### Meu nome √© Juan Pablo, aqui estar√° minha experi√™ncia no mundo da programa√ß√£o, Cloud Computing e Cyber Security.

#### Cursando Bacharelado em Sistemas de Informa√ß√£o 2/8 IFBAIANO.


<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/cristyan477/cristyan477/output/github-contribution-grid-snake-dark.svg">
  <source media=" (prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/cristyan477/cristyan477/output/github-contribution-grid-snake.svg">
  <img alt="github contribution grid snake animation" src="https://raw.githubusercontent.com/mari4souza/mari4souza/output/github-contribution-grid-snake.svg">
</picture>
<br><br>



<!--
**JuanPablo2603/JuanPablo2603** is a ‚ú® _special_ ‚ú® repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- üî≠ I‚Äôm currently working on ...
- üå± I‚Äôm currently learning ...
- üëØ I‚Äôm looking to collaborate on ...
- ü§î I‚Äôm looking for help with ...
- üí¨ Ask me about ...
- üì´ How to reach me: ...
- üòÑ Pronouns: ...
- ‚ö° Fun fact: ...
-->
